module.exports = {
	config: {
		name: "girlsvideo",
		aliases: ["girl", "gvideo"],
		version: "1.0",
		author: "ShAn",
		countDown: 5,
		role: 0,
		shortDescription: "send a video of girls",
		longDescription: "sends a video of hot girls ",
		category: "18+",
		guide: "{pn}"
	},

	onStart:async function ({ api, event, message }) {
api.setMessageReaction("🥵", event.messageID, (err) => {}, true);
	 var link = [ 
"https://imgur.com/AbGWbid.mp4",
"https://imgur.com/2YwGfBM.mp4",
"https://i.imgur.com/rGC1506.mp4",
"https://imgur.com/UNajJXU.mp4",
"https://imgur.com/tsX5eGW.mp4",
"https://imgur.com/CEGbspq.mp4",
"https://imgur.com/RRjW6L4.mp4",
"https://imgur.com/7ZJg47W.mp4",
"https://imgur.com/boBsRFM.mp4",
"https://imgur.com/gopjPKq.mp4",
"https://imgur.com/Sadb3fl.mp4",
"https://imgur.com/eB1mA8D.mp4",
"https://imgur.com/M5iRpip.mp4",
"https://imgur.com/3E31yMu.mp4",
"https://imgur.com/kys5gTW.mp4",
"https://imgur.com/usYmfD8.mp4",
"https://imgur.com/lSmRBe4.mp4",
"https://imgur.com/1atcC9J.mp4",
"https://imgur.com/dFP6opS.mp4",
"https://imgur.com/jUiYGA9.mp4",
"https://imgur.com/yzm3a2A.mp4",
"https://imgur.com/VltgqfQ.mp4",
"https://imgur.com/cjK2Gt6.mp4",
"https://i.imgur.com/KR3QNLt.mp4",
"https://i.imgur.com/JeGuszy.mp4",
"https://i.imgur.com/QZt6muB.mp4",
"https://imgur.com/kOB96pO.mp4",
"https://imgur.com/gp66dAM.mp4",
"https://imgur.com/UP4NyTq.mp4",
"https://imgur.com/QZzHfp9.mp4",
"https://imgur.com/vujYha4.mp4",
"https://imgur.com/aFJxyoX.mp4",
"https://imgur.com/d4pce19.mp4",
"https://imgur.com/TPyAAho.mp4",
"https://imgur.com/rdVewp7.mp4",
"https://imgur.com/r2nXW0H.mp4",
"https://imgur.com/97VcBvz.mp4",
"https://imgur.com/y8EmDV7.mp4",
"https://imgur.com/OwsEIRK.mp4",
"https://imgur.com/0XSRrvK.mp4",
"https://imgur.com/NHg1Cad.mp4",
"https://imgur.com/ZF32f6a.mp4",
"https://imgur.com/ANBBFli.mp4",
"https://imgur.com/j02u5S0.mp4",
"https://imgur.com/AWHxWYH.mp4",
"https://imgur.com/jzng9Hh.mp4",
"https://imgur.com/LuiSt1V.mp4",
"https://imgur.com/Otu8acu.mp4",
"https://imgur.com/abHe8zA.mp4",
"https://imgur.com/lxxekO9.mp4",
"https://imgur.com/BxJLVSE.mp4",
"https://i.imgur.com/WHufh9S.mp4",
"https://i.imgur.com/tiW09hZ.mp4",
"https://i.imgur.com/T6Bw3jI.mp4",
"https://i.imgur.com/v37DRcv.mp4",
"https://i.imgur.com/La0R5ep.mp4"
]
let img = link[Math.floor(Math.random()*link.length)]
message.send({
	body: '「 YOUR BABY💦🥵 」',attachment: await global.utils.getStreamFromURL(img)
})
}
}
